### ISSUE TITLE
[FEATURE] Create different user for labs

### ISSUE THREAD

**Issue by amortenson** [learnlinux/tuxlab-infra#11]
When SSHing into lab containers, we currently always do so as the root user. The code upon which labs are built is written such that we can only SSH as the root user, even if other users are created. We want to be able to create a new user with a unique password and SSH as that user.

**Comment by amortenson** [comment]
When doing this, might as well clean up sshd dockerfile as well... there's definitely some useless code left over there

**Comment by DerekTBrown** [comment]
This problem is solved by the proxy.
