### ISSUE TITLE
[REFACTOR] Make Ansible Provision Calls idempotent

### ISSUE THREAD

**Issue by amortenson** [learnlinux/tuxlab-infra#12]
Containers get created twice right now; just need to fix issues as they come up until vagrant provision builds cleanly

**Comment by DerekTBrown** [comment]
This is currently not working because Vagrant prohibits interactive prompts in Ansible, correct?

**Comment by amortenson** [comment]
Nope. Only thing we were going to use that for was to enter some password. Should be an easy fix; we just have to decide exactly which containers we want to restart. Also not a big deal since we won't be re-vagrant upping much in the future. Would make tinkering with the infrastructure a lot easier though.

**Comment by DerekTBrown** [comment]
It would be good to have working for Ansible Tower anyway.  Just go ahead and remove the prompt in favor of a configuration variable- which is set in two places.  The default (if not set) is "ansibletux" and it should also be set in the `config.yml`. However, **push this issue off until Alpha.2**

**Comment by DerekTBrown** [comment]
The biggest thing to tackle with this issue right now is the docker containers.  Honestly, I think the easiest (and best) approach is to simply clean the build directories and images, and start from scratch every time.  Given the primary use for re-provision is while testing code updates, this makes the most sense.

**Comment by DerekTBrown** [comment]
^^ To clarify- delete the containers we own (Swarm, DNS, Proxy) not the LabVMs.

**Comment by DerekTBrown** [comment]
Switched to using the docker_container module instead of shell, which should make calls idempotent.
