### ISSUE TITLE
[FEATURE] Let's Encrypt

### ISSUE THREAD

**Issue by DerekTBrown** [learnlinux/tuxlab-infra#13]
Because of the operation of RedRouter, we no longer need to do SSL key syncing across the SSHD Docker containers.  We do, however, need to manage key syncing across the RedRouter proxy containers, such as to enable HTTPS/SSL via Let's Encrypt.  Some key considerations:

1) This code resides in the tuxlab-ssh-proxy branch (it is really obvious in proxy.js)
2) Remember that Let's Encrypt keys expire after 90 days.  So this key needs to be updated and propagated.
3) These keys cannot be generated separately on each host.  They need to be generated once and synced.

**Comment by DerekTBrown** [comment]
REVISE:

FOR NOW: Go ahead and generate some testing keys in a new folder /local/ssl; add them to the repository and sync them to Meteor and RedRouter using ansible.

LATER: https://github.com/alex/letsencrypt-aws

**Comment by amortenson** [comment]
Test keys generated and synced; the code is in place to use the letsencrypt keys when they are obtained properly. Pushing the rest back to alpha 2

**Comment by DerekTBrown** [comment]
Implemented. To use a Let's Encrypt key, create a private key (ca.key) and a certificate (ca.pem) in ~/.tuxlab prior to installation.
