### ISSUE TITLE
[REFACTOR] Docker-SSHD

### ISSUE THREAD

**Issue by DerekTBrown** [learnlinux/tuxlab-infra#21]
- [x] The banner you created will only display on  regular SSH (and not WebSSH connections).  I think this is good in the long run- as it identifies our server. However, we need to create a separate MOTD for users once they login.  This resides in /etc/motd and needs to be edited from the alpine default.
- [x] Can we rename from docker-sshd? We have made too many changes to call it the same thing.
- [x] Remove key syncing (https://github.com/learnlinux/tuxlab-infra/issues/13)
- [ ] Post to the Docker Hub

**Comment by amortenson** [comment]
renamed in #27
