### ISSUE TITLE
[REFACTOR] Fix SSH Collision

### ISSUE THREAD

**Issue by DerekTBrown** [learnlinux/tuxlab-infra#23]

**Comment by DerekTBrown** [comment]
We need to change the CoreOS SSH Daemon default port to avoid conflicts with the proxy;

https://coreos.com/os/docs/latest/customizing-sshd.html

Problem is, if we are doing it with Ansible, this means the connection is going to be lost:

https://dmsimard.com/2016/03/15/changing-the-ssh-port-with-ansible/

**Comment by DerekTBrown** [comment]
How to fix Vagrant SSH:
https://github.com/mitchellh/vagrant/issues/3232#issuecomment-39354659>

**Comment by amortenson** [comment]
Fixed with #25
