### ISSUE TITLE
[Bug] HelixDNS with ETCD Authentication

### ISSUE THREAD

**Issue by amortenson** [learnlinux/tuxlab-infra#29]
After revoking all guest permissions to make ETCD secure, I discovered that helixDNS no longer works. We need to find a way to pass ETCD authentication info into helixdns. I created an issue in the helixdns repo asking about this. For now, we should probably disable ETCD authentication.

**Comment by amortenson** [comment]
HelixDNS hasn't been updated in two years and uses a deprecated ETCD client. It's a bit late to be thinking about this but maybe we should switch to skydns? They've discussed support for etcd authentication here: https://github.com/skynetservices/skydns/issues/228

**Comment by DerekTBrown** [comment]
For now, simply disable ETCD Authentication.  In the future, we will plan on migrating to SkyDNS.  In the meantime, work on a PR to add the authentication support.

**Comment by DerekTBrown** [comment]
I have migrated systems to SkyDNS.  However, this doesn't work in future cases because you haven't enabled ETCD Authentication for Docker.
