### ISSUE TITLE
[REFACTOR] Add Meteor Steps to Ansible Role

### ISSUE THREAD

**Issue by DerekTBrown** [learnlinux/tuxlab-infra#45]
The new version of Meteor has been released officially.  However, I am not sure that it is installed as part of the default installer.   In any case though, it seems we need to add at least the chown step from the temporary Meteor fix into the Ansible role for tuxlab-app so that the app will function properly:

https://github.com/learnlinux/tuxlab-app/issues/130

Test it with just the chown step first, and add the other rm steps only if necessary.

**Comment by DerekTBrown** [comment]
https://github.com/learnlinux/tuxlab-infra/blob/master/roles/tuxlab-app/tasks/main.yml#L31

**Comment by amortenson** [comment]
#59
