### ISSUE TITLE
Fix bug with local pexpect install

### ISSUE THREAD

**Issue by amortenson** [learnlinux/tuxlab-infra#58]
Task sometimes fails asking for user authentication; this task does not need to be run if pexpect is already installed on local machine, so the bug can be avoided by manually installing pexpect and commenting out the task for now.
https://github.com/learnlinux/tuxlab-infra/blob/master/roles/tls-ca/tasks/main.yml#L3

**Comment by DerekTBrown** [comment]
I have resolved this by adding pexpect to the list of dependencies, and automatically installing pexpect on the Tower instance that we create.
