### ISSUE TITLE
[REFACTOR] Dynamic ETCD Cluster Scaling

### ISSUE THREAD

**Issue by DerekTBrown** [learnlinux/tuxlab-infra#73]
https://github.com/coreos/etcd/issues/1016

**Comment by dobegor** [comment]
What's the status of this issue?
Is it implemented?

**Comment by DerekTBrown** [comment]
We are able to dynamically scale ETCD, but there is some swap delay in which we have to take our ETCD cluster offline.  Its currently implemented as a separate ansible playbook, so it needs to be run from Tower.
